### ISSUE TITLE
The link to the research project is dead

### ISSUE THREAD

**Issue by Hexcles** [NullHypothesis/backlogscans#2]
It seems the new link is: https://www.cs.unm.edu/~royaen/projects/gfw/index.html

Could you confirm if this is the same research project you were referring to and update the README? Thanks.

**Comment by NullHypothesis** [comment]
Thanks for reporting this, Hexcles! Yes, this is the same research project. I just updated the README in commit 21a7bb8439999fd031faafcabd34d95e3315c292.
